In [1]:
# import data libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# import modules
import video.df as df
import video.exploration as ex
from importlib import reload

In [7]:
import video.reader as r
import cv2 as cv
from video.reader import VideoReader

from typing import List, Union
from numpy.typing import ArrayLike

Plan:
- Create a function to extract diff of BGR sum in numpy. Steps:
1. Mean values of every channel per frame `df.groupby('frame').blue.mean()`
2. Sum of those values

- For every video:
1. Extract normalized lightness difference
2. Extract normalized sum of bgr channels differnce
3. Print the name of file and BGR or Ligtness
4. Print the results of zero crossing frames
5. Print the result of hazard seconds

In [ ]:
# function to extract the difference of bgr sum
def get_bgr_sum_diff(vid: Union[str, ArrayLike]) -> np.array:
    '''
    parameters:
        path: string -> path to the video
    returns:
        a numpy array with a difference in the sum of values of the 3 channels in the video:
    blue, green and red channels
    '''
    if isinstance(vid, str):
        vid, fps = VideoReader.get_vid(vid, 0)
    #frames = vid.shape[0]
    height = vid.shape[1]
    width = vid.shape[2]
    # get the average result of sum of all bgr values per frame
    avg_bgr = vid.reshape(-1, 3).sum(axis=1).reshape(-1, height*width).mean(axis = 1)
    # get the difference cd (for color difference)
    cd = np.diff(avg_bgr, 1)
    # normalize the difference, all values should be between -0.5 and 0.5
    cd = (cd - cd.min())/(cd.max() - cd.min()) - 0.5

    return cd, fps


In [3]:
path = 'videos/Banned Pokemon Seizure Scene.mp4'

In [11]:
if isinstance(path, str):
    vid, fps = VideoReader.get_vid(path, 0)
frames = vid.shape[0]
height = vid.shape[1]
width = vid.shape[2]

In [12]:
frames, height, width

(785, 100, 100)

In [17]:
# framesm height, width, channels
vid.shape

(785, 100, 100, 3)

In [28]:
# every single pixel with its BGR values
vid.reshape(-1, 3) # shape (7850000, 3)

array([[36, 36, 36],
       [34, 34, 34],
       [32, 32, 32],
       ...,
       [44, 29, 25],
       [44, 29, 25],
       [44, 29, 25]], dtype=uint8)

In [30]:
# sum of BGR values for every pixel
vid.reshape(-1, 3).sum(axis=1) # shape (7850000,)

array([108, 102,  96, ...,  98,  98,  98], dtype=uint64)

In [35]:
# array of sum of BGR values of every pixel in the frame
vid.reshape(-1, 3).sum(axis=1).reshape(-1, height*width) # shape (785, 10000)

array([[108, 102,  96, ..., 398, 399, 393],
       [108, 102,  96, ..., 398, 399, 393],
       [108, 102,  96, ..., 398, 399, 393],
       ...,
       [108, 108, 108, ...,  96,  98,  98],
       [108, 108, 108, ...,  98,  98,  98],
       [108, 108, 108, ...,  98,  98,  98]], dtype=uint64)

In [39]:
vid.reshape(-1, 3).sum(axis=1).reshape(-1, height*width).mean(axis = 1) # shape (785,)

array([314.2295, 314.2142, 314.1625, 314.0782, 313.9871, 313.9558,
       313.935 , 313.9361, 313.9446, 313.9484, 313.9413, 313.9346,
       313.9444, 313.974 , 313.9556, 313.8789, 313.8402, 313.8243,
       313.7907, 313.7877, 313.7757, 313.7766, 313.7686, 313.7626,
       313.7541, 313.6841, 313.6594, 313.6091, 313.5222, 313.484 ,
       313.3756, 313.3247, 313.2317, 313.222 , 313.2315, 313.2282,
       313.2175, 313.2377, 313.2245, 313.2318, 313.2245, 313.2318,
       313.2242, 313.2503, 313.2165, 313.2195, 313.2171, 313.2089,
       313.1711, 313.1906, 313.2462, 313.1511, 313.1345, 313.1458,
       313.1195, 313.1039, 313.1234, 313.1004, 313.1164, 313.169 ,
       313.1773, 313.1724, 313.1122, 313.0861, 313.0303, 313.0344,
       313.0445, 313.0416, 313.0305, 313.0428, 313.0305, 313.0428,
       313.0276, 313.0412, 313.0658, 313.0225, 313.0542, 313.035 ,
       313.0105, 312.9339, 312.9537, 312.94  , 312.9435, 312.9259,
       312.8988, 312.9006, 312.8799, 312.8908, 312.8868, 312.9

In [40]:
avg_bgr = vid.reshape(-1, 3).sum(axis=1).reshape(-1, height*width).mean(axis = 1)

In [49]:
avg_bgr1 = np.mean(vid.reshape(-1, 3)[:, 0].reshape((-1, height*width)), axis=1) + \
np.mean(vid.reshape(-1, 3)[:, 1].reshape((-1, height*width)), axis=1) + \
np.mean(vid.reshape(-1, 3)[:, 2].reshape((-1, height*width)), axis=1)

In [56]:
# create the mean of sum values of all channels provides same results as sum of mean values of every channel
np.sum(np.round(avg_bgr, 1) == np.round(avg_bgr1, 1))

785