In [1]:
import pandas as pd
import numpy as np
import video.df as df
from video import vid

import video.reader as r
import cv2 as cv
from video.reader import VideoReader

import re
import os
import pickle

from typing import List, Union
from numpy.typing import ArrayLike

from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
import tensorflow as tf

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

from sklearn.preprocessing import StandardScaler

import video.preprocess as pr

2023-04-14 10:59:22.078627: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
import matplotlib.pyplot as plt

In [11]:
# check if 1st file works coorect

In [7]:
path = 'videos/Banned Pokemon Seizure Scene.mp4'

In [9]:
X = pr.get_lightness_difference(path)

In [10]:
directory = 'videos1'

In [13]:
from importlib import reload

In [14]:
reload(pr)

<module 'video.preprocess' from '/Users/nadina/Documents/codeup/epilator/video/preprocess.py'>

In [15]:
# check if saves the pickle file
data = pr.get_sequence(directory=directory)

In [16]:
# check if loads correctly the pickle file
data1 = pr.get_sequence(directory=directory)

In [22]:
type(data), type(data1)

(dict, dict)

In [29]:
type(data1['Sequence'][0])

numpy.ndarray

In [30]:
X_train, y_train = pr.preprocess_ann(data)

/Users/nadina/Documents/codeup/epilator/video/preprocess.py:108: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  vectors = np.array(sq)


In [57]:
reload(pr)

<module 'video.preprocess' from '/Users/nadina/Documents/codeup/epilator/video/preprocess.py'>

In [51]:
# removed warning
X_train, y_train, sc = pr.preprocess_ann(data)

In [39]:
y_train[:2]

array([[1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [40]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=3000, activation='relu'))
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))
ann.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
ann.fit(X_train, y_train,  batch_size=64, epochs=30)

Epoch 1/30
1/1 [==============================] - 1s 852ms/step - loss: 1.6236 - accuracy: 0.2000
Epoch 2/30
1/1 [==============================] - 0s 230ms/step - loss: 9.0504 - accuracy: 0.5000
Epoch 3/30
1/1 [==============================] - 0s 234ms/step - loss: 0.6823 - accuracy: 0.8000
Epoch 4/30
1/1 [==============================] - 0s 247ms/step - loss: 2.3188 - accuracy: 0.7500
Epoch 5/30
1/1 [==============================] - 0s 227ms/step - loss: 4.4607 - accuracy: 0.6500
Epoch 6/30
1/1 [==============================] - 0s 219ms/step - loss: 2.1612 - accuracy: 0.7500
Epoch 7/30
1/1 [==============================] - 0s 228ms/step - loss: 1.7659 - accuracy: 0.7500
Epoch 8/30
1/1 [==============================] - 0s 224ms/step - loss: 1.2711 - accuracy: 0.8000
Epoch 9/30
1/1 [==============================] - 0s 216ms/step - loss: 0.1663 - accuracy: 0.9000
Epoch 10/30
1/1 [==============================] - 0s 218ms/step - loss: 0.1195 - accuracy: 0.9500
Epoch 11/30
1/1 [==

In [81]:
# hello overfitting

In [41]:
import acquire as ac

In [42]:
# test video
ac.download_video('https://www.youtube.com/watch?v=626RhBUO2tE')

True

In [67]:
reload(pr)

<module 'video.preprocess' from '/Users/nadina/Documents/codeup/epilator/video/preprocess.py'>

In [63]:
v = pr.get_lightness_difference('videos/Learn A To Z Insects For Kindergarten  A to Z  Learning Video  A To Z Reading  The Little Lumen.mp4')

In [54]:
v.reshape(-1,1).shape

(6454, 1)

In [69]:
v.shape

(7345,)

In [68]:
v = pr.single_video_padding(v, pr.max_len)

In [72]:
v.shape

(7345,)

In [73]:
v.reshape(1, -1)

array([[ 0.0288,  0.0164,  0.0852, ..., -0.872 , -0.4052,  0.8312]])

In [74]:
v = sc.transform(v.reshape(1,-1))

In [75]:
v

array([[-0.21624014, -0.20539978,  0.42143774, ..., -0.31318938,
         0.18224913, -0.20509814]])

In [78]:
ann.predict(v)

1/1 [==============================] - 0s 23ms/step


array([[9.9858201e-01, 1.3702000e-03, 4.7816076e-05]], dtype=float32)

In [77]:
pd.options.display.float_format = '{:,.2f}'.format

In [79]:
[9.9858201e-01, 1.3702000e-03, 4.7816076e-05]

[0.99858201, 0.0013702, 4.7816076e-05]

In [84]:
# detects wrong

In [82]:
y_train[:2]

array([[1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [83]:
data['ClassName'][:2]

['hazard', 'hazard']